
CREATE DATABASE IF NOT EXISTS fastersheep DEFAULT CHARACTER SET = 'utf8mb4' DEFAULT COLLATE = 'utf8mb4_unicode_ci';
USE fastersheep; CREATE TABLE IF NOT EXISTS users (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, username TEXT, password TEXT, CONSTRAINT uni_tablename_column UNIQUE (username));

USE fastersheep; CREATE TABLE IF NOT EXISTS example_entity (id BIGINT AUTO_INCREMENT PRIMARY KEY, currencies BIGINT, price DECIMAL(25, 10) NOT NULL, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
